import { chromium } from '@playwright/test';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];
page.on('pageerror', e=>errors.push(e.message));
await page.goto(process.env.SITE_URL || 'http://localhost:5173');
await page.waitForTimeout(1800);
if(await page.locator('#scene-fallback').isVisible()) throw new Error('WebGL fallback displayed');
await page.screenshot({path:'/tmp/greeting-desktop.png',fullPage:true});
await page.locator('#coffee').click();
await page.getByRole('status').filter({hasText:'Fikapeppen'}).waitFor();
await page.getByRole('button',{name:'Pausa animation'}).click();
await page.getByRole('button',{name:'Starta animation'}).waitFor();
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(400);
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Mobile overflow');
await page.screenshot({path:'/tmp/greeting-mobile.png',fullPage:true});
await page.emulateMedia({reducedMotion:'reduce'});
await page.reload();
await page.getByRole('button',{name:'Starta animation'}).waitFor();
if(errors.length) throw new Error(errors.join('\n'));
console.log('Passed: WebGL render, fika interaction, pause control, mobile layout, reduced motion, no browser errors.');
await browser.close();
